[package]
name = "gst-plugin-s3"
version = "0.1.0"
authors = ["Arun Raghavan <arun@arunraghavan.net>"]
repository = "https://github.com/ford-prefect/gst-plugin-s3"
license = "LGPL-3.0"

[dependencies]
url = "1.1"
gst-plugin = { git = "https://github.com/sdroege/gst-plugin-rs" }
#gst-plugin = { path = "../gst-plugin-rs/gst-plugin" }

[lib]
name = "gsts3"
crate-type = ["cdylib"]
