[package]
name = "gst-plugin-s3"
version = "0.1.0"
authors = ["Arun Raghavan <arun@arunraghavan.net>"]
repository = "https://github.com/ford-prefect/gst-plugin-s3"
license = "MIT/Apache-2.0"

[dependencies]
gst-plugin = { git = "https://github.com/sdroege/gst-plugin-rs" }
gst-plugin-simple = { git = "https://github.com/sdroege/gst-plugin-rs" }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs" }
hyper = "0.10"
rusoto_core = "0.28.0"
rusoto_s3 = "0.28.0"
slog = "2.0"
url = "1.1"

[lib]
name = "gsts3"
crate-type = ["cdylib"]
